name: Best Practices Assignment - Commit Phase

on:
  workflow_dispatch:
  push:
    paths:
      - "begin/**"
    branches:
      - deployment # or specify your desired branch

env:
  PROJECT_PATH: "begin"

jobs:
  lint-build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.16
          cache: "npm"
          cache-dependency-path: ${{ env.PROJECT_PATH }}/package.json

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ env.PROJECT_PATH }}

      - name: Lint
        run: npm run lint
        working-directory: ${{ env.PROJECT_PATH }}

      - name: Build
        run: npm run build
        working-directory: ${{ env.PROJECT_PATH }}

      - name: Test (core unit tests)
        run: npm run test:unit
        working-directory: ${{ env.PROJECT_PATH }}
