name: Automatically Deploy to Staging

on:
  workflow_run:
    workflows: ["Commit Phase"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Backend to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: srv-d26ei8euk2gs73c1hq00
          api-key: ${{ secrets.RENDER_TOKEN }}
      - name: Deploy Frontend to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: srv-d26f1bqdbo4c73cltmtg
          api-key: ${{ secrets.RENDER_TOKEN }}
      - name: Display deployment status
        run: |
          echo "Deployment triggered. Check the Render dashboard for deployment status."
          echo "https://dashboard.render.com"
