name: Best Practices Assignment - Automatically Deploy to Staging

on:
  workflow_run:
    workflows: ["Best Practices Assignment - Commit Phase"]
    types:
      - completed
    branches:
      - deployment

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: srv-d26ei8euk2gs73c1hq00?key=JW4tMLgtwqI
          api-key: ${{ secrets.RENDER_TOKEN }}
